SET CLIENT_ENCODING TO UTF8;
SET STANDARD_CONFORMING_STRINGS TO ON;
SET client_min_messages TO WARNING;
UPDATE final SET isotwolettercode = NULL WHERE name = 'Somaliland';
UPDATE final SET isothreelettercode = NULL WHERE name = 'Somaliland';
UPDATE final SET isotwolettercode = NULL WHERE name = 'Siachen Glacier';
UPDATE final SET isothreelettercode = NULL WHERE name = 'Siachen Glacier';
UPDATE final SET isotwolettercode = NULL WHERE name = 'Spratly Islands';
UPDATE final SET isothreelettercode = NULL WHERE name = 'Spratly Islands';
UPDATE final SET isotwolettercode = NULL WHERE name = 'Coral Sea Islands';
UPDATE final SET isothreelettercode = NULL WHERE name = 'Coral Sea Islands';
UPDATE final SET isotwolettercode = NULL WHERE name = 'Clipperton Island';
UPDATE final SET isothreelettercode = NULL WHERE name = 'Clipperton Island';
UPDATE final SET isotwolettercode = NULL WHERE name = 'US Naval Base Guantanamo Bay';
UPDATE final SET isothreelettercode = NULL WHERE name = 'US Naval Base Guantanamo Bay';
BEGIN;
COMMIT;
