SET CLIENT_ENCODING TO UTF8;
SET STANDARD_CONFORMING_STRINGS TO ON;
SET client_min_messages TO WARNING;

DROP DATABASE IF EXISTS eigeo;
CREATE DATABASE eigeo WITH OWNER = ecoinvent ENCODING = 'UTF8';
ALTER DATABASE eigeo SET search_path = public, topology;
